name: Backend Pipeline
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    uses: ismaelGTI/microHackaton-CleanCode2/.github/workflows/ci-cd-backend.yml@main
    with:
      java-version: '17'
      deploy-target: 'prod-backend1'
