name: Frontend Pipeline
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    uses: ismaelGTI/microHackaton-CleanCode2/.github/workflows/ci-cd-frontend.yml@main
    with:
      node-version: '16'
      deploy-target: 'prod-frontend1'
